### ISSUE TITLE
Criação de Carrocel do UnB Ciência

### ISSUE THREAD

**Issue by JeffersonSenaa** [ResidenciaTICBrisa/T2G7-Revista-Darcy#117]
## Descrição 
Esta issue descreve a criação do carrocel de artigos do UnB Ciência sendo um elemento comum a todas as páginas do site. O carrocel é desenvolvido como um modelo padrão do WordPress e chamado por meio do id ao carrocel em cada página.

## Tarefas
Etapas necessárias para resolução do problema:

- [x] Desenvolvimento conforme protótipo da Secom no Figma
- [x] Implementar como um modelo padrão 
- [x] Ajustar elementos e dimensão do carrocel

## Critérios de Aceitação

- [ ] O carrocel possui um botão com link para o respectivo artigo

## Recursos
Site do UnB Ciência: https://unbciencia.unb.br/

**Comment by luisfilipe3** [comment]
Os botões com links foram adicionados na Issue #129
