### ISSUE TITLE
Ajustes finais para Release 4

### ISSUE THREAD

**Issue by JeffersonSenaa** [ResidenciaTICBrisa/T2G7-Revista-Darcy#156]
## Descrição 
Serão feitos ajustes apontados durante a reunião final com a Secom.

## Tarefas
Tarefas necessárias:

Menu institucional:
- [x] Ajustar logo Darcy 
- [x] Página Notícias 
- [x] Página Mídias e Downloads
- [x] Página Contato 
- [x] Página Assine a Darcy 
- [x] Botão de voltar a home 

Ajustes gerais:
- [x] Modelo Assine a Darcy
- [x] Carrocel Instagram 
- [x] Artigo Expediente: edição 30
- [x] Dossie 

EDIÇÕES:
- [ ] Edição 29
- [ ] Edição 27
- [ ] Edição Especial

## Critérios de Aceitação

- [ ] As tarefas foram realizadas e validadas com o cliente

**Comment by luisfilipe3** [comment]
Os ajustes pedidos:
**Modelo Assine a Darcy
Carrocel Instagram**
Foram já efetuados e podem ser acompanhado através da issue #157

**Comment by JeffersonSenaa** [comment]
Ajustes desenvolvidos:

- Criação do documento Dossie 
- Botão de voltar a home no menu Darcy
- Ajustar logo Darcy

O desenvolvimento do documento pode ser acompanhado por meio da issue #159

**Comment by luisfilipe3** [comment]
Finalizei e adicionei já a página de expediente
