### ISSUE TITLE
Implementação do protótipo na instância do wordpress

### ISSUE THREAD

**Issue by Tiago1604** [ResidenciaTICBrisa/T2G7-Revista-Darcy#73]
## Descrição 
Implementar todas as páginas criadas no protótipo do figma e suas respectivas navegabilidades.

## Tarefas
Etapas necessárias para resolução do problema:

- [x] Implementação página 1 - home
- [x] Implementação página 2 - Página da edição
- [x] Implementação página 3 - Página de artigo
- [x] Implementação página 4 - Página de todas as edições
- [x] Implementação página 5 - Página de projeto de extensão
- [x] Implementar os menus que foram validados

## Critérios de Aceitação

- [x] Todas as tarefas terem sido realizadas e estarem na instância do wordpress

## Recursos
WordPress e Figma.

**Comment by luisfilipe3** [comment]
Fico responsável pela implementação da página 4 - Página de todas as edições
